export declare const documentTypeEnum: import("node_modules/drizzle-orm/pg-core/index.cjs").PgEnum<["NATIONAL_ID", "DRIVERS_LICENSE", "VEHICLE_PAPERS", "LOCAL_GOV_LETTER", "BUSINESS_LICENSE", "BUSINESS_REGISTRATION"]>;
export declare const verificationStatusEnum: import("node_modules/drizzle-orm/pg-core/index.cjs").PgEnum<["PENDING", "APPROVED", "REJECTED"]>;
export declare const documents: import("node_modules/drizzle-orm/pg-core/table.cjs").PgTableWithColumns<{
    name: "documents";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "id";
            tableName: "documents";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "user_id";
            tableName: "documents";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        documentType: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "document_type";
            tableName: "documents";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "NATIONAL_ID" | "DRIVERS_LICENSE" | "VEHICLE_PAPERS" | "LOCAL_GOV_LETTER" | "BUSINESS_LICENSE" | "BUSINESS_REGISTRATION";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["NATIONAL_ID", "DRIVERS_LICENSE", "VEHICLE_PAPERS", "LOCAL_GOV_LETTER", "BUSINESS_LICENSE", "BUSINESS_REGISTRATION"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        fileUrl: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "file_url";
            tableName: "documents";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 500;
        }>;
        fileName: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "file_name";
            tableName: "documents";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        fileSize: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "file_size";
            tableName: "documents";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        mimeType: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "mime_type";
            tableName: "documents";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 100;
        }>;
        verificationStatus: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "verification_status";
            tableName: "documents";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "PENDING" | "APPROVED" | "REJECTED";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["PENDING", "APPROVED", "REJECTED"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        verifiedBy: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "verified_by";
            tableName: "documents";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        verifiedAt: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "verified_at";
            tableName: "documents";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        rejectionReason: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "rejection_reason";
            tableName: "documents";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "created_at";
            tableName: "documents";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core/index.cjs").PgColumn<{
            name: "updated_at";
            tableName: "documents";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type Document = typeof documents.$inferSelect;
export type NewDocument = typeof documents.$inferInsert;
export declare const DocumentType: {
    readonly NATIONAL_ID: "NATIONAL_ID";
    readonly DRIVERS_LICENSE: "DRIVERS_LICENSE";
    readonly VEHICLE_PAPERS: "VEHICLE_PAPERS";
    readonly LOCAL_GOV_LETTER: "LOCAL_GOV_LETTER";
    readonly BUSINESS_LICENSE: "BUSINESS_LICENSE";
    readonly BUSINESS_REGISTRATION: "BUSINESS_REGISTRATION";
};
export declare const VerificationStatus: {
    readonly PENDING: "PENDING";
    readonly APPROVED: "APPROVED";
    readonly REJECTED: "REJECTED";
};
export type DocumentTypeType = (typeof DocumentType)[keyof typeof DocumentType];
export type VerificationStatusType = (typeof VerificationStatus)[keyof typeof VerificationStatus];
