export declare const notificationTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["sms", "email", "push"]>;
export declare const notificationCategoryEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["auth", "account", "order", "shipment", "payment", "system", "marketing"]>;
export declare const notificationStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["pending", "sent", "failed", "delivered"]>;
export declare const notifications: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "notifications";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "notifications";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "notifications";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        type: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "type";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "push" | "email" | "sms";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["sms", "email", "push"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        recipient: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "recipient";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        sender: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "sender";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 100;
        }>;
        category: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "category";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "auth" | "account" | "order" | "shipment" | "payment" | "system" | "marketing";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["auth", "account", "order", "shipment", "payment", "system", "marketing"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        purpose: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "purpose";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 100;
        }>;
        subject: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "subject";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 255;
        }>;
        message: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "message";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        preview: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "preview";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 200;
        }>;
        showInApp: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "show_in_app";
            tableName: "notifications";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isRead: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_read";
            tableName: "notifications";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        readAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "read_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        reference: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "reference";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            length: 100;
        }>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "pending" | "sent" | "failed" | "delivered";
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["pending", "sent", "failed", "delivered"];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        response: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "response";
            tableName: "notifications";
            dataType: "json";
            columnType: "PgJson";
            data: unknown;
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        error: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "error";
            tableName: "notifications";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        metadata: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "metadata";
            tableName: "notifications";
            dataType: "json";
            columnType: "PgJson";
            data: {
                [key: string]: any;
                orderId?: number;
                shipmentId?: number;
                paymentId?: number;
                deepLink?: string;
                actionUrl?: string;
            };
            driverParam: unknown;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {
            $type: {
                [key: string]: any;
                orderId?: number;
                shipmentId?: number;
                paymentId?: number;
                deepLink?: string;
                actionUrl?: string;
            };
        }>;
        sentAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "sent_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        deliveredAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "delivered_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "notifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;
export declare const NotificationCategory: {
    readonly AUTH: "auth";
    readonly ACCOUNT: "account";
    readonly ORDER: "order";
    readonly SHIPMENT: "shipment";
    readonly PAYMENT: "payment";
    readonly SYSTEM: "system";
    readonly MARKETING: "marketing";
};
export declare const NotificationType: {
    readonly SMS: "sms";
    readonly EMAIL: "email";
    readonly PUSH: "push";
};
export declare const NotificationStatus: {
    readonly PENDING: "pending";
    readonly SENT: "sent";
    readonly FAILED: "failed";
    readonly DELIVERED: "delivered";
};
export declare const CommonNotificationPurposes: {
    readonly OTP_VERIFICATION: "otp_verification";
    readonly PASSWORD_RESET: "password_reset";
    readonly ACCOUNT_CREATED: "account_created";
    readonly ACCOUNT_UPDATED: "account_updated";
    readonly PROFILE_COMPLETED: "profile_completed";
    readonly ORDER_CONFIRMED: "order_confirmed";
    readonly ORDER_SHIPPED: "order_shipped";
    readonly ORDER_DELIVERED: "order_delivered";
    readonly ORDER_CANCELLED: "order_cancelled";
    readonly PAYMENT_SUCCESS: "payment_success";
    readonly PAYMENT_FAILED: "payment_failed";
    readonly PAYMENT_REMINDER: "payment_reminder";
    readonly SHIPMENT_CREATED: "shipment_created";
    readonly SHIPMENT_IN_TRANSIT: "shipment_in_transit";
    readonly SHIPMENT_DELIVERED: "shipment_delivered";
    readonly SYSTEM_MAINTENANCE: "system_maintenance";
    readonly FEATURE_ANNOUNCEMENT: "feature_announcement";
    readonly PROMO_CAMPAIGN: "promo_campaign";
    readonly SEASONAL_OFFER: "seasonal_offer";
};
export type NotificationCategoryType = (typeof NotificationCategory)[keyof typeof NotificationCategory];
export type NotificationTypeType = (typeof NotificationType)[keyof typeof NotificationType];
export type NotificationStatusType = (typeof NotificationStatus)[keyof typeof NotificationStatus];
