export const ExceptionConstants = {
  BadRequestCodes: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',
    FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
  },
  NotFoundCodes: {
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  },
  ForbiddenCodes: {
    ACCESS_DENIED: 'ACCESS_DENIED',
    INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  },
};
