import {
  members,
  baptismStatusEnum,
  memberGenderEnum,
  memberMaritalStatusEnum,
  type Member,
  type NewMember,
} from "./tables/members"
import { users, roleEnum, type User, type NewUser, type RoleType } from "./tables/user"
import {
  userChurchMemberships,
  userChurchMembershipRoleEvents,
  membershipStatusEnum,
  type UserChurchMembership,
  type NewUserChurchMembership,
  type UserChurchMembershipRoleEvent,
  type NewUserChurchMembershipRoleEvent,
} from "./tables/userChurchMemberships"
import { zones, type Zone, type NewZone } from "./tables/zones"
import { departments, type Department, type NewDepartment } from "./tables/departments"
import { churches, type Church, type NewChurch } from "./tables/churches"
import { families, type Family, type NewFamily } from "./tables/families"
import {
  visitors,
  visitorFollowups,
  visitorFollowupStatusEnum,
  visitorSourceEnum,
  type Visitor,
  type NewVisitor,
  type VisitorFollowup,
  type NewVisitorFollowup,
} from "./tables/visitors"
import { memberZones, type MemberZone, type NewMemberZone } from "./tables/memberZones"
import { memberDepartments, type MemberDepartment, type NewMemberDepartment } from "./tables/memberDepartments"
import { notifications, type Notification, type NewNotification } from "./tables/notifications"
import { importJobs, importRows, duplicateCandidates, mergeActions, type ImportJob, type ImportRow, type DuplicateCandidate, type MergeAction } from "./tables/dataQuality"
import { familyRelationships, familyConnectionSuggestions, milestoneNotificationRules, lifecycleMilestones, type FamilyRelationship, type FamilyConnectionSuggestion, type MilestoneNotificationRule, type LifecycleMilestone } from "./tables/familyLifecycle"
import { attendanceSessionMetadata, attendanceSnapshots, attendanceRiskProfiles, attendanceRiskHistory } from "./tables/attendanceV2"
import { serviceCadenceEnum, riskSeverityEnum } from "./tables/attendanceV2"
import {
  messageTemplates,
  campaigns,
  campaignRecipients,
  messageDeliveries,
  campaignEvents,
  communicationChannelEnum,
  campaignStatusEnum,
  deliveryStatusEnum,
  type MessageTemplate,
  type NewMessageTemplate,
  type Campaign,
  type NewCampaign,
  type CampaignRecipient,
  type NewCampaignRecipient,
  type MessageDelivery,
  type NewMessageDelivery,
  type CampaignEvent,
  type NewCampaignEvent,
} from "./tables/communications"
import {
  serviceTypes,
  serviceSessions,
  attendanceHeadcounts,
  attendanceCheckins,
  engagementRiskDefaults,
  engagementRiskSettings,
  engagementRiskFlags,
  serviceSessionStatusEnum,
  checkinSourceEnum,
  type ServiceType,
  type NewServiceType,
  type ServiceSession,
  type NewServiceSession,
  type AttendanceHeadcount,
  type NewAttendanceHeadcount,
  type AttendanceCheckin,
  type NewAttendanceCheckin,
  type EngagementRiskDefault,
  type NewEngagementRiskDefault,
  type EngagementRiskSetting,
  type NewEngagementRiskSetting,
  type EngagementRiskFlag,
  type NewEngagementRiskFlag,
} from "./tables/attendance"
import {
  relationshipRoleEnum,
  connectionStatusEnum,
  suggestionStatusEnum,
  milestoneTypeEnum,
  milestoneChannelEnum,
  milestoneNotifyTargetEnum,
  milestoneStatusEnum,
} from "./tables/familyLifecycle"
import {
  importJobStatusEnum,
  importModeEnum,
  duplicateCandidateStatusEnum,
} from "./tables/dataQuality"
import {
  prayerRequests,
  prayerRequestStatusEnum,
  type PrayerRequest,
  type NewPrayerRequest,
} from "./tables/prayerRequests"

// Import all relations
import {
  churchesRelations,
  zonesRelations,
  departmentsRelations,
  membersRelations,
  memberZonesRelations,
  memberDepartmentsRelations,
  familiesRelations,
  visitorsRelations,
  visitorFollowupsRelations,
  usersRelations,
  userChurchMembershipsRelations,
  userChurchMembershipRoleEventsRelations,
  serviceTypesRelations,
  serviceSessionsRelations,
  attendanceHeadcountsRelations,
  attendanceCheckinsRelations,
  engagementRiskSettingsRelations,
  engagementRiskFlagsRelations,
  messageTemplatesRelations,
  campaignsRelations,
  campaignRecipientsRelations,
  messageDeliveriesRelations,
  campaignEventsRelations,
  prayerRequestsRelations,
} from "./tables/relations"

export {
  users,
  roleEnum,
  baptismStatusEnum,
  memberGenderEnum,
  memberMaritalStatusEnum,
  visitorFollowupStatusEnum,
  visitorSourceEnum,
  membershipStatusEnum,
  serviceCadenceEnum,
  riskSeverityEnum,
  communicationChannelEnum,
  campaignStatusEnum,
  deliveryStatusEnum,
  serviceSessionStatusEnum,
  checkinSourceEnum,
  relationshipRoleEnum,
  connectionStatusEnum,
  suggestionStatusEnum,
  milestoneTypeEnum,
  milestoneChannelEnum,
  milestoneNotifyTargetEnum,
  milestoneStatusEnum,
  importJobStatusEnum,
  importModeEnum,
  duplicateCandidateStatusEnum,
  prayerRequestStatusEnum,
  userChurchMemberships,
  userChurchMembershipRoleEvents,
  zones,
  departments,
  members,
  churches,
  families,
  visitors,
  visitorFollowups,
  memberZones,
  memberDepartments,
  notifications,
  importJobs,
  importRows,
  duplicateCandidates,
  mergeActions,
  familyRelationships,
  familyConnectionSuggestions,
  milestoneNotificationRules,
  lifecycleMilestones,
  attendanceSessionMetadata,
  attendanceSnapshots,
  attendanceRiskProfiles,
  attendanceRiskHistory,
  serviceTypes,
  serviceSessions,
  attendanceHeadcounts,
  attendanceCheckins,
  engagementRiskDefaults,
  engagementRiskSettings,
  engagementRiskFlags,
  messageTemplates,
  campaigns,
  campaignRecipients,
  messageDeliveries,
  campaignEvents,
  prayerRequests,
  // Export relations for Drizzle ORM
  churchesRelations,
  zonesRelations,
  departmentsRelations,
  membersRelations,
  memberZonesRelations,
  memberDepartmentsRelations,
  familiesRelations,
  visitorsRelations,
  visitorFollowupsRelations,
  usersRelations,
  userChurchMembershipsRelations,
  userChurchMembershipRoleEventsRelations,
  serviceTypesRelations,
  serviceSessionsRelations,
  attendanceHeadcountsRelations,
  attendanceCheckinsRelations,
  engagementRiskSettingsRelations,
  engagementRiskFlagsRelations,
  messageTemplatesRelations,
  campaignsRelations,
  campaignRecipientsRelations,
  messageDeliveriesRelations,
  campaignEventsRelations,
  prayerRequestsRelations,
  // Type exports
  type User,
  type NewUser,
  type RoleType,
  type UserChurchMembership,
  type NewUserChurchMembership,
  type UserChurchMembershipRoleEvent,
  type NewUserChurchMembershipRoleEvent,
  type Member,
  type NewMember,
  type Zone,
  type NewZone,
  type Department,
  type NewDepartment,
  type Church,
  type NewChurch,
  type Family,
  type NewFamily,
  type Visitor,
  type NewVisitor,
  type VisitorFollowup,
  type NewVisitorFollowup,
  type MemberZone,
  type NewMemberZone,
  type MemberDepartment,
  type NewMemberDepartment,
  type Notification,
  type NewNotification,
  type ImportJob,
  type ImportRow,
  type DuplicateCandidate,
  type MergeAction,
  type FamilyRelationship,
  type FamilyConnectionSuggestion,
  type MilestoneNotificationRule,
  type LifecycleMilestone,
  type ServiceType,
  type NewServiceType,
  type ServiceSession,
  type NewServiceSession,
  type AttendanceHeadcount,
  type NewAttendanceHeadcount,
  type AttendanceCheckin,
  type NewAttendanceCheckin,
  type EngagementRiskDefault,
  type NewEngagementRiskDefault,
  type EngagementRiskSetting,
  type NewEngagementRiskSetting,
  type EngagementRiskFlag,
  type NewEngagementRiskFlag,
  type MessageTemplate,
  type NewMessageTemplate,
  type Campaign,
  type NewCampaign,
  type CampaignRecipient,
  type NewCampaignRecipient,
  type MessageDelivery,
  type NewMessageDelivery,
  type CampaignEvent,
  type NewCampaignEvent,
  type PrayerRequest,
  type NewPrayerRequest,
}
