import { members, type Member, type NewMember } from "./tables/members"
import { users, type User, type NewUser } from "./tables/user"
import { zones, type Zone, type NewZone } from "./tables/zones"
import { churches, type Church, type NewChurch } from "./tables/churches"
import { families, type Family, type NewFamily } from "./tables/families"
import { visitors, visitorFollowups, type Visitor, type NewVisitor, type VisitorFollowup, type NewVisitorFollowup } from "./tables/visitors"
import { memberZones, type MemberZone, type NewMemberZone } from "./tables/memberZones"
import { notifications, type Notification, type NewNotification } from "./tables/notifications"
import { importJobs, importRows, duplicateCandidates, mergeActions, type ImportJob, type ImportRow, type DuplicateCandidate, type MergeAction } from "./tables/dataQuality"
import { familyRelationships, familyConnectionSuggestions, milestoneNotificationRules, lifecycleMilestones, type FamilyRelationship, type FamilyConnectionSuggestion, type MilestoneNotificationRule, type LifecycleMilestone } from "./tables/familyLifecycle"
import { attendanceSessionMetadata, attendanceSnapshots, attendanceRiskProfiles, attendanceRiskHistory } from "./tables/attendanceV2"
import {
  messageTemplates,
  campaigns,
  campaignRecipients,
  messageDeliveries,
  campaignEvents,
  type MessageTemplate,
  type NewMessageTemplate,
  type Campaign,
  type NewCampaign,
  type CampaignRecipient,
  type NewCampaignRecipient,
  type MessageDelivery,
  type NewMessageDelivery,
  type CampaignEvent,
  type NewCampaignEvent,
} from "./tables/communications"
import {
  serviceTypes,
  serviceSessions,
  attendanceHeadcounts,
  attendanceCheckins,
  engagementRiskDefaults,
  engagementRiskSettings,
  engagementRiskFlags,
  type ServiceType,
  type NewServiceType,
  type ServiceSession,
  type NewServiceSession,
  type AttendanceHeadcount,
  type NewAttendanceHeadcount,
  type AttendanceCheckin,
  type NewAttendanceCheckin,
  type EngagementRiskDefault,
  type NewEngagementRiskDefault,
  type EngagementRiskSetting,
  type NewEngagementRiskSetting,
  type EngagementRiskFlag,
  type NewEngagementRiskFlag,
} from "./tables/attendance"

// Import all relations
import {
  churchesRelations,
  zonesRelations,
  membersRelations,
  memberZonesRelations,
  familiesRelations,
  visitorsRelations,
  visitorFollowupsRelations,
  usersRelations,
  serviceTypesRelations,
  serviceSessionsRelations,
  attendanceHeadcountsRelations,
  attendanceCheckinsRelations,
  engagementRiskSettingsRelations,
  engagementRiskFlagsRelations,
  messageTemplatesRelations,
  campaignsRelations,
  campaignRecipientsRelations,
  messageDeliveriesRelations,
  campaignEventsRelations,
} from "./tables/relations"

export {
  users,
  zones,
  members,
  churches,
  families,
  visitors,
  visitorFollowups,
  memberZones,
  notifications,
  importJobs,
  importRows,
  duplicateCandidates,
  mergeActions,
  familyRelationships,
  familyConnectionSuggestions,
  milestoneNotificationRules,
  lifecycleMilestones,
  attendanceSessionMetadata,
  attendanceSnapshots,
  attendanceRiskProfiles,
  attendanceRiskHistory,
  serviceTypes,
  serviceSessions,
  attendanceHeadcounts,
  attendanceCheckins,
  engagementRiskDefaults,
  engagementRiskSettings,
  engagementRiskFlags,
  messageTemplates,
  campaigns,
  campaignRecipients,
  messageDeliveries,
  campaignEvents,
  // Export relations for Drizzle ORM
  churchesRelations,
  zonesRelations,
  membersRelations,
  memberZonesRelations,
  familiesRelations,
  visitorsRelations,
  visitorFollowupsRelations,
  usersRelations,
  serviceTypesRelations,
  serviceSessionsRelations,
  attendanceHeadcountsRelations,
  attendanceCheckinsRelations,
  engagementRiskSettingsRelations,
  engagementRiskFlagsRelations,
  messageTemplatesRelations,
  campaignsRelations,
  campaignRecipientsRelations,
  messageDeliveriesRelations,
  campaignEventsRelations,
  // Type exports
  type User,
  type NewUser,
  type Member,
  type NewMember,
  type Zone,
  type NewZone,
  type Church,
  type NewChurch,
  type Family,
  type NewFamily,
  type Visitor,
  type NewVisitor,
  type VisitorFollowup,
  type NewVisitorFollowup,
  type MemberZone,
  type NewMemberZone,
  type Notification,
  type NewNotification,
  type ImportJob,
  type ImportRow,
  type DuplicateCandidate,
  type MergeAction,
  type FamilyRelationship,
  type FamilyConnectionSuggestion,
  type MilestoneNotificationRule,
  type LifecycleMilestone,
  type ServiceType,
  type NewServiceType,
  type ServiceSession,
  type NewServiceSession,
  type AttendanceHeadcount,
  type NewAttendanceHeadcount,
  type AttendanceCheckin,
  type NewAttendanceCheckin,
  type EngagementRiskDefault,
  type NewEngagementRiskDefault,
  type EngagementRiskSetting,
  type NewEngagementRiskSetting,
  type EngagementRiskFlag,
  type NewEngagementRiskFlag,
  type MessageTemplate,
  type NewMessageTemplate,
  type Campaign,
  type NewCampaign,
  type CampaignRecipient,
  type NewCampaignRecipient,
  type MessageDelivery,
  type NewMessageDelivery,
  type CampaignEvent,
  type NewCampaignEvent,
}
